### ISSUE TITLE
Golang support

### ISSUE THREAD

**Issue by medifle** [Mohamed3nan/jetbrains-darcula-theme#1]
Like this theme!

It has almost the same color as my Goland Darcula when syntax matches. But many can be improved:

- package name
- package method/function/variable
- type

**Comment by Mohamed3nan** [comment]
> Like this theme!
> 
> It has almost the same color as my Goland Darcula when syntax matches. But many can be improved:
> 
> * package name
> * package method/function/variable
> * type

It will be very helpful if you post screenshots for these examples:
- package name
- package method/function/variable
- type

just to compare the colors and make some edits because I do not have GoLand IDE.

**Comment by medifle** [comment]
Take an example from [here](https://github.com/medifle/simpleloc/blob/master/processor/processor.go):

## Comparison 1
GoLand:
<img width="902" alt="goland" src="https://user-images.githubusercontent.com/13296643/123171471-bb403c80-d430-11eb-9262-b159c5662536.png">

VSCode:
<img width="902" alt="vscode" src="https://user-images.githubusercontent.com/13296643/123171529-cdba7600-d430-11eb-9b8d-a2d14a879953.png">

Diff:
- struct type
  - `LanguageFeature`
  - `Language`
  - `File`

- package name
  - `base64`
  - `fmt`
  - `filepath`
  - `jsoniter`

- package method
  - `DecodeString`
  - `Sprintf`
  - `Unmarshal`
  - `Printf`
  - `Println`
  - `Ext`
  - `Errorf`
  - `ToLower`

- constant
  - `languages`

- built-in function
  - `panic`
  - `len`

- `+` operator at line 87

From my observation,  package method call shares the same color as function call.

`err` is a mystery to me, some `err` are highlighted in GoLand, others are not.


## Comparison 2
Goland:
<img width="761" alt="goland2" src="https://user-images.githubusercontent.com/13296643/123174782-8b476800-d435-11eb-97d3-cdf1824a53f5.png">

VSCode:
<img width="761" alt="vscode2" src="https://user-images.githubusercontent.com/13296643/123174793-8edaef00-d435-11eb-99f5-c00378ac5134.png">


Diff:

- package name
  - `processor`

- constant
  - all the purple italic const

- type
  - `stateType`
  - `machine`

- receiver
  - `m` in `resetState` method

- character
  - ` `, `\t`, `\n`, `\r` at line 36


Let me know if you need other info, I am glad to provide more. BTW GoLand has a 30 days trial if there is a need to extract the color.

**Comment by Mohamed3nan** [comment]
Thank you for your contribution.

Since VSCode relies on textmate scopes as a selector for theme which sometimes can not differentiate some syntax like Goland.
I cannot highlight these syntaxes:
- struct type
- constant
- type
- receiver

I downloaded GoLand and from my observation, it uses some machine learning for highlighting.


However, these elements are improved:
- package name
- package method
- built-in functions
- operators
- characters

and a new version released, you can update the theme now ;)
