### ISSUE TITLE
c++ struct color and method color are too close

### ISSUE THREAD

**Issue by bigdogs** [Mohamed3nan/jetbrains-darcula-theme#2]
Hi,   

 Color of c++ struct and method are too close comparing to Clion, Is it possible to change the color of c++ struct  like "clion"? 

vscode.
![image](https://user-images.githubusercontent.com/20614926/134620188-0b3419fa-d0d6-4c2e-8589-eb173e4378fe.png)

clion
![image](https://user-images.githubusercontent.com/20614926/134620225-574dccc9-0fdc-4fa4-a700-9c9cc7ef4da8.png)

**Comment by Mohamed3nan** [comment]
Thanks, 
fixed and it will be included in the next update.
![image](https://user-images.githubusercontent.com/19733801/178110952-96983d0e-6af7-413b-bb6b-55d972271b8d.png)
