### ISSUE TITLE
Colors of HTML tag content in JSX

### ISSUE THREAD

**Issue by brneor** [Mohamed3nan/jetbrains-darcula-theme#4]
The color of content of HTML tags differ between `.html` files and `.js` files when using JSX

HTML:
![image](https://user-images.githubusercontent.com/5962898/164453952-3c685480-52ac-4004-853a-c64b6c774237.png)

JSX:
![image](https://user-images.githubusercontent.com/5962898/164454120-c5750567-804d-4f88-9caf-3d5ae435fe04.png)

I solved this by adding this block of code in my `settings.json`:

```json
"editor.tokenColorCustomizations": {
  "[JetBrains Darcula Theme]": {
    "textMateRules": [
      {
        "scope": ["meta.jsx.children"],
        "settings": {
          "foreground": "#A9B7C6"
        }
      }
    ]
  }
},
```

I think it would be nice to have this by default in the theme. I didn't want to make a PR yet because I don't know if you have some standard in your theme file, but if you point me a direction I'll gladly do it. :)

**Comment by Mohamed3nan** [comment]
Thanks,
fixed and it will be included in the next update.
![image](https://user-images.githubusercontent.com/19733801/178111004-09530db5-4025-453b-9a3d-fedf18633d3c.png)
