### ISSUE TITLE
c++ include color different from CLion

### ISSUE THREAD

**Issue by yangtzech** [Mohamed3nan/jetbrains-darcula-theme#5]
Hi,

c++ include color in VSCode is different from CLion. Is it possible to change the color like CLion?

This is what CLion shows:
![image](https://user-images.githubusercontent.com/41911522/192231233-d290ca45-f444-447e-a459-a7c26b703466.png)

This is what VSCode shows:
![image](https://user-images.githubusercontent.com/41911522/192231301-c5874204-dea9-40df-8df5-86c2e957b044.png)

**Comment by bukowa** [comment]
I have exact opposite problem with same colors :)

**Comment by Mohamed3nan** [comment]
Thank you for reporting. The issue has been fixed and a new update has just been released. 
![c++](https://user-images.githubusercontent.com/19733801/232235940-d69254c1-b709-49d9-adc1-bc77c76f8559.png)
