### ISSUE TITLE
Variable name in Quotation do not highlight

### ISSUE THREAD

**Issue by huhx** [Mohamed3nan/jetbrains-darcula-theme#7]
use in dart:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/15972372/197479464-cc3b7efb-ea0b-486e-a4d3-c40d14826967.png">

**Comment by huhx** [comment]
This configuration can work: "editor.semanticHighlighting.enabled": true,

**Comment by Mohamed3nan** [comment]
> This configuration can work: "editor.semanticHighlighting.enabled": true,

Careful because this option will make a lot of things confusing, but it's ok if it fixes your issue.

GL
