### ISSUE TITLE
Improve ERROR  in *.log files

### ISSUE THREAD

**Issue by alkatar21** [Mohamed3nan/jetbrains-darcula-theme#8]
Currently, much is already handled correctly for *.log files, but there is also an inconvenient combination. While WARNING is highlighted, ERROR is displayed in the same color as INFO. The necessary keys can be seen [here](https://github.com/microsoft/vscode/blob/main/extensions/log/syntaxes/log.tmLanguage.json#L60).

**Comment by Mohamed3nan** [comment]
Thank you for reporting. The issue has been fixed and a new update has just been released.
![error](https://user-images.githubusercontent.com/19733801/232236009-a6ab1ccd-a9c5-4170-893b-c53112d9eef0.png)
